name: shiftend
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  flutter: 1.20.1
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # for firestore
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.15
  firebase_auth: ^0.16.1

  table_calendar: ^2.2.3

  # state
  state_notifier: ^0.5.0
  flutter_state_notifier: ^0.4.2
  freezed_annotation:
  provider: ^4.3.0

  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
  pedantic: any

  json_serializable:
  build_runner:
  freezed:

flutter:
  uses-material-design: true